<?php

declare(strict_types=1);

return array (
  0 => 
  array (
    'slug' => 'ps-intro',
    'order' => 1,
    'title' => 'Prisma ORM intro',
    'level' => 'Conceptos',
    'minutes' => 25,
    'summary' => 'Type-safe database client.',
    'concepts' => 
    array (
      0 => 'prisma',
      1 => 'orm',
      2 => 'typescript',
    ),
    'sections' => 
    array (
      0 => 
      array (
        'heading' => 'Prisma',
        'body' => '**ORM** moderno Node/TS — schema declarative, migrations, type-safe client autogenerated.',
        'code' => 'console.log(\'Practica: ps-intro\');',
      ),
      1 => 
      array (
        'heading' => 'Stack',
        'body' => 'PostgreSQL, MySQL, SQLite, MongoDB — curso PostgreSQL base SQL.',
        'code' => 'console.log(\'Practica: ps-intro\');',
      ),
    ),
    'exercises' => 
    array (
      0 => 
      array (
        'type' => 'choice',
        'question' => '¿Prisma Client?',
        'options' => 
        array (
          0 => 'Autogenerated type-safe queries',
          1 => 'Manual SQL strings',
          2 => 'CSS framework',
        ),
        'answer' => 'Autogenerated type-safe queries',
        'explanation' => 'prisma.user.findMany().',
        'pro_tip' => 'Compare Eloquent Laravel.',
      ),
      1 => 
      array (
        'type' => 'choice',
        'question' => '¿schema.prisma?',
        'options' => 
        array (
          0 => 'Single source models + datasource',
          1 => 'PHP config',
          2 => 'Docker file',
        ),
        'answer' => 'Single source models + datasource',
        'explanation' => 'Define models here.',
        'pro_tip' => 'npx prisma init.',
      ),
    ),
  ),
  1 => 
  array (
    'slug' => 'ps-schema',
    'order' => 2,
    'title' => 'Schema y modelos',
    'level' => 'Fundamentos',
    'minutes' => 35,
    'summary' => 'Models, fields, relations.',
    'concepts' => 
    array (
      0 => 'model',
      1 => 'field',
      2 => 'relation',
    ),
    'sections' => 
    array (
      0 => 
      array (
        'heading' => 'Models',
        'body' => 'model User { id Int @id @default(autoincrement()) email String @unique posts Post[] }',
        'code' => 'model User { id Int @id ... }',
      ),
      1 => 
      array (
        'heading' => 'Relations',
        'body' => '1-N, N-M implicit join table — @relation fields references.',
        'code' => 'model User { id Int @id ... }',
      ),
    ),
    'exercises' => 
    array (
      0 => 
      array (
        'type' => 'choice',
        'question' => '¿@id @default(autoincrement())?',
        'options' => 
        array (
          0 => 'Primary key auto increment',
          1 => 'Optional field',
          2 => 'Delete cascade',
        ),
        'answer' => 'Primary key auto increment',
        'explanation' => 'Prisma schema syntax.',
        'pro_tip' => 'uuid() alternative PK.',
      ),
      1 => 
      array (
        'type' => 'contains',
        'question' => 'Escribe model User',
        'must_contain' => 
        array (
          0 => 'model User',
        ),
        'hint' => 'model User { id Int @id ... }',
        'explanation' => 'Define entity.',
        'pro_tip' => '@@map rename table.',
      ),
    ),
  ),
  2 => 
  array (
    'slug' => 'ps-migrate',
    'order' => 3,
    'title' => 'Migrations',
    'level' => 'Práctica',
    'minutes' => 30,
    'summary' => 'prisma migrate dev/deploy.',
    'concepts' => 
    array (
      0 => 'migrate',
      1 => 'dev',
      2 => 'deploy',
    ),
    'sections' => 
    array (
      0 => 
      array (
        'heading' => 'Migrations',
        'body' => 'npx prisma migrate dev --name init — SQL files prisma/migrations/',
        'code' => 'console.log(\'Practica: ps-migrate\');',
      ),
      1 => 
      array (
        'heading' => 'Prod',
        'body' => 'prisma migrate deploy — CI/CD apply pending migrations.',
        'code' => 'console.log(\'Practica: ps-migrate\');',
      ),
    ),
    'exercises' => 
    array (
      0 => 
      array (
        'type' => 'choice',
        'question' => '¿migrate dev?',
        'options' => 
        array (
          0 => 'Dev creates migration + applies',
          1 => 'Production only',
          2 => 'Delete DB',
        ),
        'answer' => 'Dev creates migration + applies',
        'explanation' => 'Shadow database validates.',
        'pro_tip' => 'Compare Laravel migrations.',
      ),
      1 => 
      array (
        'type' => 'choice',
        'question' => '¿db push vs migrate?',
        'options' => 
        array (
          0 => 'push prototype no history; migrate versioned',
          1 => 'Same',
          2 => 'push production',
        ),
        'answer' => 'push prototype no history; migrate versioned',
        'explanation' => 'Prod always migrate.',
        'pro_tip' => 'Never db push prod.',
      ),
    ),
  ),
  3 => 
  array (
    'slug' => 'ps-crud',
    'order' => 4,
    'title' => 'CRUD y queries',
    'level' => 'Práctica',
    'minutes' => 35,
    'summary' => 'findMany, create, update, delete.',
    'concepts' => 
    array (
      0 => 'crud',
      1 => 'where',
      2 => 'include',
    ),
    'sections' => 
    array (
      0 => 
      array (
        'heading' => 'Queries',
        'body' => 'prisma.post.findMany({ where: { published: true }, include: { author: true } })',
        'code' => 'console.log(\'Practica: ps-crud\');',
      ),
      1 => 
      array (
        'heading' => 'Transactions',
        'body' => 'prisma.$transaction([createUser, createProfile]) — atomic.',
        'code' => 'console.log(\'Practica: ps-crud\');',
      ),
    ),
    'exercises' => 
    array (
      0 => 
      array (
        'type' => 'choice',
        'question' => '¿include?',
        'options' => 
        array (
          0 => 'Eager load relations',
          1 => 'SQL injection',
          2 => 'CSS',
        ),
        'answer' => 'Eager load relations',
        'explanation' => 'Like Eloquent with().',
        'pro_tip' => 'select specific fields reduce payload.',
      ),
      1 => 
      array (
        'type' => 'choice',
        'question' => '¿upsert?',
        'options' => 
        array (
          0 => 'Update or insert',
          1 => 'Delete all',
          2 => 'Backup',
        ),
        'answer' => 'Update or insert',
        'explanation' => 'where create update pattern.',
        'pro_tip' => 'Idempotent sync jobs.',
      ),
    ),
  ),
  4 => 
  array (
    'slug' => 'ps-relations',
    'order' => 5,
    'title' => 'Relations avanzadas',
    'level' => 'Intermedio',
    'minutes' => 35,
    'summary' => 'N-M, cascading, referential.',
    'concepts' => 
    array (
      0 => 'many-to-many',
      1 => 'cascade',
      2 => 'referential',
    ),
    'sections' => 
    array (
      0 => 
      array (
        'heading' => 'N-M',
        'body' => 'Implicit _CategoryToPost or explicit join model custom fields.',
        'code' => 'console.log(\'Practica: ps-relations\');',
      ),
      1 => 
      array (
        'heading' => 'onDelete',
        'body' => 'Cascade, SetNull, Restrict — FK behavior Prisma maps.',
        'code' => 'console.log(\'Practica: ps-relations\');',
      ),
    ),
    'exercises' => 
    array (
      0 => 
      array (
        'type' => 'choice',
        'question' => '¿onDelete Cascade?',
        'options' => 
        array (
          0 => 'Delete children when parent deleted',
          1 => 'Prevent delete',
          2 => 'Random',
        ),
        'answer' => 'Delete children when parent deleted',
        'explanation' => 'Schema relation attribute.',
        'pro_tip' => 'Soft delete pattern alternative.',
      ),
      1 => 
      array (
        'type' => 'choice',
        'question' => '¿Prisma vs raw SQL?',
        'options' => 
        array (
          0 => 'Prisma $queryRaw when complex',
          1 => 'Never raw',
          2 => 'Always raw',
        ),
        'answer' => 'Prisma $queryRaw when complex',
        'explanation' => 'Escape hatch exists.',
        'pro_tip' => 'Prisma optimize N+1.',
      ),
    ),
  ),
  5 => 
  array (
    'slug' => 'ps-prod',
    'order' => 6,
    'title' => 'Prisma en producción',
    'level' => 'Producción',
    'minutes' => 30,
    'summary' => 'Connection pool, accelerate, seed.',
    'concepts' => 
    array (
      0 => 'pool',
      1 => 'accelerate',
      2 => 'seed',
    ),
    'sections' => 
    array (
      0 => 
      array (
        'heading' => 'Connection pool',
        'body' => 'PgBouncer, Prisma Accelerate — serverless connection limits.',
        'code' => 'console.log(\'Practica: ps-prod\');',
      ),
      1 => 
      array (
        'heading' => 'Seed',
        'body' => 'prisma db seed — dev/staging baseline data script.',
        'code' => 'console.log(\'Practica: ps-prod\');',
      ),
    ),
    'exercises' => 
    array (
      0 => 
      array (
        'type' => 'choice',
        'question' => '¿Serverless + Postgres issue?',
        'options' => 
        array (
          0 => 'Connection exhaustion — use pooler',
          1 => 'No issue',
          2 => 'Use SQLite prod',
        ),
        'answer' => 'Connection exhaustion — use pooler',
        'explanation' => 'Lambda many concurrent.',
        'pro_tip' => 'Curso Supabase pooler similar.',
      ),
      1 => 
      array (
        'type' => 'choice',
        'question' => '¿Prisma Studio?',
        'options' => 
        array (
          0 => 'GUI browse edit data dev',
          1 => 'Production monitoring',
          2 => 'CSS tool',
        ),
        'answer' => 'GUI browse edit data dev',
        'explanation' => 'npx prisma studio.',
        'pro_tip' => 'Compare pgAdmin PostgreSQL.',
      ),
    ),
  ),
  6 => 
  array (
    'slug' => 'prisma-orm-produccion',
    'order' => 7,
    'title' => 'Patrones de producción y resiliencia',
    'level' => 'Producción',
    'minutes' => 35,
    'summary' => 'Patrones de producción y resiliencia — cierre avanzado de Prisma ORM.',
    'concepts' => 
    array (
      0 => 'production',
      1 => 'resilience',
      2 => 'ops',
    ),
    'sections' => 
    array (
      0 => 
      array (
        'heading' => 'Patrones en producción',
        'body' => 'Aplica lo aprendido en Prisma ORM a un entorno real: límites, fallos parciales, idempotencia y métricas que importan en producción.',
        'code' => '// Structured logging en Node/Next
import pino from \'pino\';

export const logger = pino({
  level: process.env.LOG_LEVEL ?? \'info\',
  redact: [\'req.headers.authorization\', \'password\'],
});

logger.info({ route: \'/api/users\', ms: 42 }, \'request completed\');',
      ),
      1 => 
      array (
        'heading' => 'Operación continua',
        'body' => 'Documenta runbooks, define SLOs, automatiza verificaciones post-deploy y revisa alertas antes de que los usuarios las reporten.',
        'code' => '// Structured logging en Node/Next
import pino from \'pino\';

export const logger = pino({
  level: process.env.LOG_LEVEL ?? \'info\',
  redact: [\'req.headers.authorization\', \'password\'],
});

logger.info({ route: \'/api/users\', ms: 42 }, \'request completed\');',
      ),
    ),
    'exercises' => 
    array (
      0 => 
      array (
        'type' => 'choice',
        'question' => '¿Qué revisar antes de un deploy a producción?',
        'options' => 
        array (
          0 => 'Health checks, migraciones y rollback plan',
          1 => 'Solo el color del botón',
          2 => 'Nada si compila',
        ),
        'answer' => 'Health checks, migraciones y rollback plan',
        'explanation' => 'Un checklist de deploy evita incidentes evitables.',
        'pro_tip' => 'Automatiza el checklist en CI/CD cuando sea posible.',
      ),
      1 => 
      array (
        'type' => 'choice',
        'question' => '¿Señal de que necesitas observabilidad mejor?',
        'options' => 
        array (
          0 => 'Descubres fallos por tweets de usuarios',
          1 => 'Todo funciona en local',
          2 => 'Tienes logs estructurados',
        ),
        'answer' => 'Descubres fallos por tweets de usuarios',
        'explanation' => 'Si no tienes métricas/trazas, operas a ciegas.',
        'pro_tip' => 'Define SLI/SLO antes de escalar el equipo.',
      ),
    ),
  ),
  7 => 
  array (
    'slug' => 'prisma-orm-operaciones',
    'order' => 8,
    'title' => 'Observabilidad, debugging y checklist de deploy',
    'level' => 'Avanzado',
    'minutes' => 35,
    'summary' => 'Observabilidad, debugging y checklist de deploy — cierre avanzado de Prisma ORM.',
    'concepts' => 
    array (
      0 => 'production',
      1 => 'resilience',
      2 => 'ops',
    ),
    'sections' => 
    array (
      0 => 
      array (
        'heading' => 'Patrones en producción',
        'body' => 'Aplica lo aprendido en Prisma ORM a un entorno real: límites, fallos parciales, idempotencia y métricas que importan en producción.',
        'code' => '// Structured logging en Node/Next
import pino from \'pino\';

export const logger = pino({
  level: process.env.LOG_LEVEL ?? \'info\',
  redact: [\'req.headers.authorization\', \'password\'],
});

logger.info({ route: \'/api/users\', ms: 42 }, \'request completed\');',
      ),
      1 => 
      array (
        'heading' => 'Operación continua',
        'body' => 'Documenta runbooks, define SLOs, automatiza verificaciones post-deploy y revisa alertas antes de que los usuarios las reporten.',
        'code' => '// Structured logging en Node/Next
import pino from \'pino\';

export const logger = pino({
  level: process.env.LOG_LEVEL ?? \'info\',
  redact: [\'req.headers.authorization\', \'password\'],
});

logger.info({ route: \'/api/users\', ms: 42 }, \'request completed\');',
      ),
    ),
    'exercises' => 
    array (
      0 => 
      array (
        'type' => 'choice',
        'question' => '¿Qué revisar antes de un deploy a producción?',
        'options' => 
        array (
          0 => 'Health checks, migraciones y rollback plan',
          1 => 'Solo el color del botón',
          2 => 'Nada si compila',
        ),
        'answer' => 'Health checks, migraciones y rollback plan',
        'explanation' => 'Un checklist de deploy evita incidentes evitables.',
        'pro_tip' => 'Automatiza el checklist en CI/CD cuando sea posible.',
      ),
      1 => 
      array (
        'type' => 'choice',
        'question' => '¿Señal de que necesitas observabilidad mejor?',
        'options' => 
        array (
          0 => 'Descubres fallos por tweets de usuarios',
          1 => 'Todo funciona en local',
          2 => 'Tienes logs estructurados',
        ),
        'answer' => 'Descubres fallos por tweets de usuarios',
        'explanation' => 'Si no tienes métricas/trazas, operas a ciegas.',
        'pro_tip' => 'Define SLI/SLO antes de escalar el equipo.',
      ),
    ),
  ),
);
