<?php

declare(strict_types=1);

return [
    ['slug' => 'ps-intro', 'order' => 1, 'title' => 'Prisma ORM intro', 'level' => 'Conceptos', 'minutes' => 25, 'summary' => 'Type-safe database client.', 'concepts' => ['prisma', 'orm', 'typescript'], 'sections' => [
        ['heading' => 'Prisma', 'body' => '**ORM** moderno Node/TS — schema declarative, migrations, type-safe client autogenerated.'],
        ['heading' => 'Stack', 'body' => 'PostgreSQL, MySQL, SQLite, MongoDB — curso PostgreSQL base SQL.'],
    ], 'exercises' => [
        ['type' => 'choice', 'question' => '¿Prisma Client?', 'options' => ['Autogenerated type-safe queries', 'Manual SQL strings', 'CSS framework'], 'answer' => 'Autogenerated type-safe queries', 'explanation' => 'prisma.user.findMany().', 'pro_tip' => 'Compare Eloquent Laravel.'],
        ['type' => 'choice', 'question' => '¿schema.prisma?', 'options' => ['Single source models + datasource', 'PHP config', 'Docker file'], 'answer' => 'Single source models + datasource', 'explanation' => 'Define models here.', 'pro_tip' => 'npx prisma init.'],
    ]],
    ['slug' => 'ps-schema', 'order' => 2, 'title' => 'Schema y modelos', 'level' => 'Fundamentos', 'minutes' => 35, 'summary' => 'Models, fields, relations.', 'concepts' => ['model', 'field', 'relation'], 'sections' => [
        ['heading' => 'Models', 'body' => 'model User { id Int @id @default(autoincrement()) email String @unique posts Post[] }'],
        ['heading' => 'Relations', 'body' => '1-N, N-M implicit join table — @relation fields references.'],
    ], 'exercises' => [
        ['type' => 'choice', 'question' => '¿@id @default(autoincrement())?', 'options' => ['Primary key auto increment', 'Optional field', 'Delete cascade'], 'answer' => 'Primary key auto increment', 'explanation' => 'Prisma schema syntax.', 'pro_tip' => 'uuid() alternative PK.'],
        ['type' => 'contains', 'question' => 'Escribe model User', 'must_contain' => ['model User'], 'hint' => 'model User { id Int @id ... }', 'explanation' => 'Define entity.', 'pro_tip' => '@@map rename table.'],
    ]],
    ['slug' => 'ps-migrate', 'order' => 3, 'title' => 'Migrations', 'level' => 'Práctica', 'minutes' => 30, 'summary' => 'prisma migrate dev/deploy.', 'concepts' => ['migrate', 'dev', 'deploy'], 'sections' => [
        ['heading' => 'Migrations', 'body' => 'npx prisma migrate dev --name init — SQL files prisma/migrations/'],
        ['heading' => 'Prod', 'body' => 'prisma migrate deploy — CI/CD apply pending migrations.'],
    ], 'exercises' => [
        ['type' => 'choice', 'question' => '¿migrate dev?', 'options' => ['Dev creates migration + applies', 'Production only', 'Delete DB'], 'answer' => 'Dev creates migration + applies', 'explanation' => 'Shadow database validates.', 'pro_tip' => 'Compare Laravel migrations.'],
        ['type' => 'choice', 'question' => '¿db push vs migrate?', 'options' => ['push prototype no history; migrate versioned', 'Same', 'push production'], 'answer' => 'push prototype no history; migrate versioned', 'explanation' => 'Prod always migrate.', 'pro_tip' => 'Never db push prod.'],
    ]],
    ['slug' => 'ps-crud', 'order' => 4, 'title' => 'CRUD y queries', 'level' => 'Práctica', 'minutes' => 35, 'summary' => 'findMany, create, update, delete.', 'concepts' => ['crud', 'where', 'include'], 'sections' => [
        ['heading' => 'Queries', 'body' => 'prisma.post.findMany({ where: { published: true }, include: { author: true } })'],
        ['heading' => 'Transactions', 'body' => 'prisma.$transaction([createUser, createProfile]) — atomic.'],
    ], 'exercises' => [
        ['type' => 'choice', 'question' => '¿include?', 'options' => ['Eager load relations', 'SQL injection', 'CSS'], 'answer' => 'Eager load relations', 'explanation' => 'Like Eloquent with().', 'pro_tip' => 'select specific fields reduce payload.'],
        ['type' => 'choice', 'question' => '¿upsert?', 'options' => ['Update or insert', 'Delete all', 'Backup'], 'answer' => 'Update or insert', 'explanation' => 'where create update pattern.', 'pro_tip' => 'Idempotent sync jobs.'],
    ]],
    ['slug' => 'ps-relations', 'order' => 5, 'title' => 'Relations avanzadas', 'level' => 'Intermedio', 'minutes' => 35, 'summary' => 'N-M, cascading, referential.', 'concepts' => ['many-to-many', 'cascade', 'referential'], 'sections' => [
        ['heading' => 'N-M', 'body' => 'Implicit _CategoryToPost or explicit join model custom fields.'],
        ['heading' => 'onDelete', 'body' => 'Cascade, SetNull, Restrict — FK behavior Prisma maps.'],
    ], 'exercises' => [
        ['type' => 'choice', 'question' => '¿onDelete Cascade?', 'options' => ['Delete children when parent deleted', 'Prevent delete', 'Random'], 'answer' => 'Delete children when parent deleted', 'explanation' => 'Schema relation attribute.', 'pro_tip' => 'Soft delete pattern alternative.'],
        ['type' => 'choice', 'question' => '¿Prisma vs raw SQL?', 'options' => ['Prisma $queryRaw when complex', 'Never raw', 'Always raw'], 'answer' => 'Prisma $queryRaw when complex', 'explanation' => 'Escape hatch exists.', 'pro_tip' => 'Prisma optimize N+1.'],
    ]],
    ['slug' => 'ps-prod', 'order' => 6, 'title' => 'Prisma en producción', 'level' => 'Producción', 'minutes' => 30, 'summary' => 'Connection pool, accelerate, seed.', 'concepts' => ['pool', 'accelerate', 'seed'], 'sections' => [
        ['heading' => 'Connection pool', 'body' => 'PgBouncer, Prisma Accelerate — serverless connection limits.'],
        ['heading' => 'Seed', 'body' => 'prisma db seed — dev/staging baseline data script.'],
    ], 'exercises' => [
        ['type' => 'choice', 'question' => '¿Serverless + Postgres issue?', 'options' => ['Connection exhaustion — use pooler', 'No issue', 'Use SQLite prod'], 'answer' => 'Connection exhaustion — use pooler', 'explanation' => 'Lambda many concurrent.', 'pro_tip' => 'Curso Supabase pooler similar.'],
        ['type' => 'choice', 'question' => '¿Prisma Studio?', 'options' => ['GUI browse edit data dev', 'Production monitoring', 'CSS tool'], 'answer' => 'GUI browse edit data dev', 'explanation' => 'npx prisma studio.', 'pro_tip' => 'Compare pgAdmin PostgreSQL.'],
    ]],
];
